language: cpp
sudo: required

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
           - g++-10
      env:
         - MATRIX_EVAL="CC=gcc-10 && CXX=g++-10"

before_install:
- eval "${MATRIX_EVAL}"

compiler:
- g++

branches:
  only:
  - dev

script:
- cd $TRAVIS_BUILD_DIR
- cmake -G "Unix Makefiles" .
- make -j 4
