language: cpp
sudo: required

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
           - gcc-9.0
      env:
         - MATRIX_EVAL="CC=gcc-9.0 && CXX=g++-9.0"

before_install:
    - eval "${MATRIX_EVAL}

compiler:
- gcc

branches:
  only:
  - master
  - dev

script:
- cmake -G "Unix Makefiles" ../
- make -j 4
